import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Button, useTheme, Text, Avatar, Grid } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

const MyComponent = () => {
  const { theme } = useTheme();

  return (
    <div>
      <Text
        css={{
          color: "$blue800",
          fontSize: "$sm",
          padding: "$2 $4",
        }}
      >
        Using tokens
      </Text>
      <p
        style={{
          color: theme.colors.primary.value,
          fontSize: theme.fontSizes.sm.value,
          padding: `${theme.space[2].value} ${theme.space[4].value}`,
        }}
      >
        Using color theme value
      </p>
    </div>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button>Click me</Button>
        <MyComponent />
        <Text css={{ background: "$myColor" }}>NextUI colors</Text>
        <Grid.Container gap={2}>
          <Grid>
            <Avatar
              squared
              src="https://i.pravatar.cc/150?u=a042581f4e29026024d"
            />
          </Grid>
          <Grid>
            <Avatar squared text="Junior" />
          </Grid>
          <Grid>
            <Avatar
              squared
              src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
            />
          </Grid>
          <Grid>
            <Avatar squared text="Jane" />
          </Grid>
          <Grid>
            <Avatar
              squared
              src="https://i.pravatar.cc/150?u=a04258114e29026702d"
            />
          </Grid>
          <Grid>
            <Avatar squared text="Joe" />
          </Grid>
        </Grid.Container>
        <Grid.Container gap={2}>
          <Grid>
            <Avatar text="JR" size="xs" />
          </Grid>
          <Grid>
            <Avatar
              src="https://i.pravatar.cc/150?u=a042581f4e29026024d"
              size="sm"
            />
          </Grid>
          <Grid>
            <Avatar text="Joe" size="md" />
          </Grid>
          <Grid>
            <Avatar
              src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
              size="lg"
            />
          </Grid>
          <Grid>
            <Avatar text="John" size="xl" />
          </Grid>
          <Grid>
            <Avatar
              src="https://i.pravatar.cc/150?u=a04258114e29026702d"
              css={{ size: "$20" }}
            />
          </Grid>
        </Grid.Container>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
